### ISSUE TITLE
Overriding this in called function

### ISSUE THREAD

**Issue by akinnee** [neurosnap/cofx#7]
Any reason to use fn.call here?

https://github.com/neurosnap/cofx/blob/master/src/effect.ts#L29

It's breaking sequelize because it changes the value of this. 

Can you change:
```
const gen = fn.call(this, ...args);
```
To:
```
const gen = fn(...args);
```

**Comment by neurosnap** [comment]
does it work with `yield call([sequalize, 'method']);`?

**Comment by akinnee** [comment]
Not sure but I opened a PR. https://github.com/neurosnap/cofx/pull/8

**Comment by akinnee** [comment]
Yeah it works with the array syntax. I see why you're doing it that way. Babel converts the spread operator to an apply call anyway so you still need something to set this to.

**Comment by akinnee** [comment]
Code example in case anyone else runs into this:

```
const pages = yield call([store.page, 'findAll', {
    where: { orgId },
  }]);
```
